# Generated by Django 2.2 on 2019-04-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('subjectName', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('tagline', models.CharField(max_length=255, null=True)),
                ('writtenBy', models.CharField(default='Christina Roberts', max_length=255)),
            ],
        ),
    ]
